sudo: required
services:
  - docker

before_install:
  - docker build -t xiaoqingyuan/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true xiaoqingyuan/react-test npm test

after_success:
  - docker build -t xiaoqingyuan/multi-client:latest ./client
  - docker build -t xiaoqingyuan/multi-nginx:latest ./nginx
  - docker build -t xiaoqingyuan/multi-server:latest ./server
  - docker build -t xiaoqingyuan/multi-worker:latest ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push xiaoqingyuan/multi-client:latest
  - docker push xiaoqingyuan/multi-nginx:latest
  - docker push xiaoqingyuan/multi-server:latest
  - docker push xiaoqingyuan/multi-worker:latest

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-009853298662"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
